blank_issues_enabled: false
contact_links:
  - name: Smart Wallet Docs
    url: https://www.smartwallet.dev/guides/react-native-integration
    about: Developer documentation to integrate Coinbase Smart Wallet using MWP SDK
